#.github/workflows/android.yml
name: Android CI

on:
   push:
        branches: [ "main" ]
   pull_request:
        branches: [ "main" ]

jobs:
   build:
        runs-on: ubuntu-latest
        steps:
  # 1. Preleva il codice
        - name: Checkout repository
          uses: actions/checkout@v4
  # 2. Installa l’SDK Android (platform-tools, build-tools, emulator ecc.)
        - name: Set up Android SDK
          uses: android-actions/setup-android@v3
  # 3. Imposta il JDK 17
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
               java-version: '17'
               distribution: 'temurin'
  #4. Salva la cartella di cache di Gradle (~/.gradle/caches + wrapper) tra un job e l’altro. Al
  # run successivo GitHub Actions riutilizza quelle dipendenze anziché riscaricarle da Maven
  #Central/Google, riducendo di parecchi minuti (e banda) il tempo di build.
        - name: Cache Gradle packages
          uses: actions/cache@v4
          with:
               path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
               key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
               restore-keys: |
                            ${{ runner.os }}-gradle-
        - name: Grant execute permission for gradlew
          run: chmod +x gradlew
        - name: Build with Gradle
          run: ./gradlew build
        - name: Run lint check
          run: ./gradlew lint
        - name: Test Debug UnitTest
          run: ./gradlew testDebugUnitTest
        - name: Assemble Release APK
          run: ./gradlew assembleRelease
        - name: Upload Release APK
          uses: actions/upload-artifact@v4
          with:
               name: app-release
               path: app/build/outputs/apk/release/app-release-unsigned.apk